services:
  server:
    image: node:20
    container_name: meewarp-server
    working_dir: /app
    command: >-
      sh -c "npm install && npm start"
    env_file:
      - server/.env
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://host.docker.internal:27017/meewarp
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
      - ./server/uploads:/app/uploads

  client:
    image: node:20
    container_name: meewarp-client
    working_dir: /app
    command: >-
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    env_file:
      - client/.env
    environment:
      VITE_API_BASE_URL: http://server:5000/api
      VITE_PROXY_TARGET: http://server:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  server_node_modules:
  client_node_modules:
